### PR TITLE
Add slow mode AHK

### PR DESCRIPTION
**Pull request by jstack1414**
Slow mode prevents a user from typing a charected within a given time of the previous key entry (typing a key resets the timer). This can be used to prevent the technicans from being able to type at a reasonable speed. Alt+s to enter slow mode Alt+f to enter fast mode (eseentially disable it by assigning the hotkeys to type the letter that is pressed).

### CODE REVIEW

**Comment by llamositopia** [comment]
I love the functionality, although I have a few concerns with the implementation:

1. Is it better to move the assignment to `LastTime` inside the `if` statement right below it? That way if someone types 5 keys and the 5th is more than `Delay` away from the 1st, it will type the 1st and 5th.

2. Is assigning a HotKey to every numerical key necessary? I feel it would be better and more encompassing to use an Input handle, read the value typed (regardless of what kind of character it is) and handle from there.

**Comment by jstack14** [comment]
1. That is also a good approach. The original intent was if you got too impatient it'd reset the timer, but I think in practice what you suggested would be better because it'd be a bit more usable, but still annoying.

2. I'll look into using an input handle. I have never used Autohotkey before so i didn't know exactly what i should be using. I'll give this a try tonight or in the next couple days!

**Comment by jstack1414** [comment]
I've explore this a bit more and I am running into some issues with an input handle approach.
I can do something like shown below (with the timing logic put in)
```
!s::
LoopInput()
Return

LoopInput() {
    Input, UserInput, L1 I
    {
        Send %UserInput%
        SetTimer, LoopInput, -1 ; Loop once because Input only catches one input
        MsgBox, 0, "Input recieved", %UserInput%, 1
        Return
    }
    Return
}
!Escape::ExitApp
```
But when a user tries to press backspace (or alt+escape for that matter), Input doesn't receive it and actually blocks it. I can't use the `v` option to let characters go through either because then I can't throttle the input (unless i did something weird like send backspace after ever letter I wanted to delete but that seems really hacky). Also, if I make alt, shift, etc as EndKeys it consumes the input and fails on things like capitalization.

@llamositopia did you have any insight into how I could use an Input handle to solve this?

**Comment by niboty** [comment]
I think using an input handle will solve it but I noticed the script currently doesn't block spaces. But resets the timer on them. So if you type a sentence fast enough you just get all spaces. I feel like spaces should be blocked as well.

I also found having the delay set around 100 is perfect for being annoying but not so obvious something tricky is happening. Hope to see it pissing off some scammers soon!

**Comment by LlemonDuck** [comment]
Closing due to inactivity

**Pull request closed without merging**
