### PR TITLE
AWS Remote Control (API Only)

### PR DESCRIPTION
**Pull request by yukihyou**
Initial base for Serverless Remote Control API

### CODE REVIEW

**Comment by niboty** [comment]
Awesome base functionality. I say we merge it so people can start working on some of the programs for the VM as well as a better front end to limit the chance of any incorrect data being sent. Maybe use a set of dropdown menus to add options like color, ect. and use text boxes for the messages. Have the front end build the JSON rather then users type it. 

But all that relies on us figuring out what we can use it for on the VM. Right now what I can think of is Error Messages, Calendar Appointments, Txt/Facebook messages. We could probably build a listener that would start up different ahk scripts as well. So viewers could vote on how to troll the scammers. 

This is a gamechanger, lets get started!

**Comment by llamositopia** [comment]
@TheDevFreak @yukihyou keep in mind here the massive amount of security to be watching out for. Obviously with the nature of this application, I would love to have it in the repo, but want to make sure that it is safe to do so. Since you both have been working together on this, I suggest you two consider some ways to limit the freedom of the data structure.

For example, giving explicit command types within the action JSON, only available from a select structure. Even if `raw` is an option for it, it limits the damage that can be done through a "normal" method. By implementing `messagebox`, `image`, etc. command types you remove the ability for a malicious or injecting call to the client.

**Comment by TheDevFreak** [comment]
@llamositopia You could POST any `action` you want. Specifically my client (#15) only supports `messagebox` and `showimage` My client can't execute code via the `messagebox` function. The only way I could see it being able to would be via showimage, and you would need to craft an image that can break out of windows photo viewer (though i do plan to change it to using a tkinter window or something  else)

**Comment by yukihyou** [comment]
The API doesn't validate anything, it just passes `action` and `data` verbatim. If the client app is written to accept `bluescreen` as an action and generate an actual BSOD, that's up to the client.

This was done deliberately, as it allows someone to develop the "two ends" of the connection using any data format, without changing anything in the API.

The API itself is secure in the sense that both ends need to be using the same `clientID` (suggest a UUID, hostname, or something unique per device) otherwise there will be no communication, and an instance-wide Key is needed to send/receive anything at all. This dual verification allows for multiple "controller-client" pairs per API setup. Further, the pending messages time out after two hours (configurable) so there won't be arbitrary commands just waiting for random clients when they poll the first time.

Given that an abuser would need to know all of the below to have any impact, I believe it's limited to only willing-party connections:
- The URL of your particular instance of the API
- The API Key you set when you installed your instance
- A clientID of a valid listening client
- When your client is actively listening (within 2h)

**Pull request merged**
